spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/geomax}
    username: ${DB_USER:geomax}
    password: ${DB_PASSWORD:geomax}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-me-please-change-me-please-32b}
