apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dating-app.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: {{ include "dating-app.name" . }} }
  template:
    metadata:
      labels: { app: {{ include "dating-app.name" . }} }
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "{{ .Values.env.DB_URL }}"
            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
            - name: APP_JWT_SECRET
              value: "{{ .Values.env.APP_JWT_SECRET }}"
